site_name: Learn

repo_url: https://github.com/Vasanthabalaji01/Learn

theme:
  name: material
  palette:
    - scheme: default
      primary: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: img/Mr.Cloudexplorer_logo.png
  favicon: img/Mr.Cloudexplorer_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - header.autohide
    - navigation.tabs

nav:
  - Home: index.md
  - About: about.md
  - Linux:
    - Index: linux/linux.md
    - Basics: linux/basics/basics.md
    - Commands: linux/commands/commands.md
    - Bash:
      - Basics: linux/bash/bash.md
      - Tasks:
        - List: linux/bash/tasks/tasks.md
        - Task 1: linux/bash/tasks/task1.md
        - Task 2: linux/bash/tasks/task2.md
        - Task 3: linux/bash/tasks/task3.md
        - Task 4: linux/bash/tasks/task4.md
        - Task 5: linux/bash/tasks/task5.md
        - Task 6: linux/bash/tasks/task6.md
        - Task 7: linux/bash/tasks/task7.md
        - Task 8: linux/bash/tasks/task8.md
        - Task 9: linux/bash/tasks/task9.md
        - Task 10: linux/bash/tasks/task10.md
    - Project: linux/project/project.md
  - Networking:
    - Index: networking/networking.md
    - Basics:
      - Intro: networking/basic_concepts/basic_concepts.md
      - OSI Model: networking/basic_concepts/osi_model/osi_model.md
      - IP Addresses: networking/basic_concepts/ip_address/ip_address.md
      - MAC Addresses: networking/basic_concepts/mac_address/mac_address.md
      - Routing and Switching: networking/basic_concepts/routing_switching/routing_switching.md
      - TCP/IP: networking/basic_concepts/tcp_ip/tcp_ip.md
      - TCP and UDP: networking/basic_concepts/tcp_udp/tcp-udp.md
      - DNS: networking/basic_concepts/dns/dns.md
      - VPN: networking/basic_concepts/vpn/vpn.md
      - TLS and SSL: networking/basic_concepts/tls_ssl/tls_ssl.md
      - Firewall: networking/basic_concepts/firewall/firewall.md
    - Protocols/Ports: networking/protocols_ports/protocols_ports.md
    - Tools:
      - Intro: networking/tools/tools.md
      - CISCO Packet Tracer: networking/tools/cisco_packet_tracer/cisco_packet_tracer.md
  - Code:
    - Intro: code/code.md
    - Python:
      - Index: code/python/python.md
      - Setup: code/python/setup/setup.md
      - Basics: code/python/basics/basics.md
      - Package Managers: code/python/package_managers/package_managers.md
      - DSA: code/python/dsa/dsa.md
      - OOP: code/python/oop/oop.md
      - Advance: code/python/advance/advance.md
      - Libraries: code/python/libraries/libraries.md
      - Automation: code/python/automation/automation.md
      - Web Application:
        - Index: code/python/web_application/web_application.md
        - Flask: code/python/web_application/flask/flask.md
        - Django: code/python/web_application/django/django.md
        - FastAPI: code/python/web_application/fastapi/fastapi.md
        - Project: code/python/web_application/project.md
      - Testing: code/python/testing/testing.md
      - Remove: code/python/remove/remove.md
    - React: code/react/react.md
    - Node.js: code/nodejs/nodejs.md
    - PHP: code/php/php.md
    - Ruby: code/ruby/ruby.md
  - Database:
    - Intro: database/database.md
    - SQL:
      - Basics: database/sql/basics/basics.md
      - SQLite: database/sql/sqlite/sqlite.md
      - Microsoft SQL Server: database/sql/microsoft_sql_server/microsoft_sql_server.md
      - MySQL: database/sql/mysql/mysql.md
    - NoSQL:
      - Basics: database/nosql/basics/basics.md
      - DynamoDB: database/nosql/dynamo_db/dynamo_db.md
      - MongoDB: database/nosql/mongo_db/mongo_db.md
  - Web Server:
    - Index: webserver/webserver.md
    - Basics: webserver/basics/basics.md
    - Servers:
      - Apache: webserver/servers/apache/apache.md
      - Nginx: webserver/servers/nginx/nginx.md
      - Windows Server: webserver/servers/windows_server/windows_server.md
  - Cloud:
    - Index: cloud/cloud.md
    - Basics: cloud/basic_concepts/basic_concepts.md
    - AWS:
      - Index: cloud/aws/aws.md
      - Basics: cloud/aws/basic_concepts/basic_concepts.md
      - Frameworks: cloud/aws/framework/framework.md
      - Services: cloud/aws/services/services.md
      - AWS CLI: cloud/aws/aws_cli/aws_cli.md
      - Project:
        - Cloud Resume: cloud/projects/cloud_resume_aws.md
        - More: https://vasanthabalaji01.github.io/AWS/
    - Azure:
      - Index: cloud/azure/azure.md
      - Basics: cloud/azure/basic_concepts/basic_concept.md
      - Frameworks: cloud/azure/framework/framework.md
      - Services: cloud/azure/services/services.md
      - Azure CLI: cloud/azure/azure_cli/azure_cli.md
      - Project:
        - Cloud Resume: cloud/projects/cloud_resume_azure.md
        - More: https://vasanthabalaji01.github.io/Azure/
  - DevOps:
    - Index: devops/devops.md
    - Basics: devops/basics/basics.md
    - Tools:
      - List: devops/tools/tools.md
      - Git GitHub: devops/tools/git_github/git_github.md
      - Ansible: devops/tools/ansible/ansible.md
      - Docker: devops/tools/docker/docker.md
      - Puppet: devops/tools/puppet/puppet.md
      - Jenkins: devops/tools/jenkins/jenkins.md
      - Chef: devops/tools/chef/chef.md
      - Nagios: devops/tools/nagios/nagios.md
      - Kubernetes: devops/tools/k8s/k8s.md
      - Terraform: devops/tools/terraform/terraform.md
      - Prometheus: devops/tools/prometheus/prometheus.md
      - Grafana: devops/tools/grafana/grafana.md
  - Security:
    - Index: security/security.md
    - Basics: security/basics/basics.md
    - Standardization/Frameworks:
      - Intro: security/Standardization_Frameworks/Standardization_Frameworks.md
      - OWASP: security/Standardization_Frameworks/owasp/owasp.md
      - CIS: security/Standardization_Frameworks/cis/cis.md
    - Tools: security/tools/tools.md
    - Practice:
      - Labs: security/practice/labs/labs.md
      - Vuln Machine: security/practice/vuln_machin/vuln_machin.md
      - CTF: security/practice/ctf/ctf.md
  - Random:
    - Index: random/random.md
    - API: random/api/api.md
    - Figma: random/figma/figma.md
    - Flameshot: random/flameshot/flameshot.md
    - Math: random/math/math.md
    - Putty: random/putty/putty.md
    - VScode: random/vscode/vscode.md
    - Xmind: random/xmind/xmind.md
    - Notion: random/notion/notion.md
    - MKDocs: random/mkdocs/mkdocs.md
  - Coures:
    - Index: cources/coures.md
    - Tech Fundamentals: cources/tech_fun.md
  - Mindfulness: Mindfulness/Mindfulness.md
    

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Vasanthabalaji01
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vasanthabalaji
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mrcloudexplorer
